<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>group13_project_report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="group13_project_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="group13_project_report_files/libs/quarto-html/quarto.js"></script>
<script src="group13_project_report_files/libs/quarto-html/popper.min.js"></script>
<script src="group13_project_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="group13_project_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="group13_project_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="group13_project_report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="group13_project_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="group13_project_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="group13_project_report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<div style="text-align:center; font-size: 22px; font-weight: bold;">
<p><strong>PARALYMPICS 2024</strong></p>
</div>
<div style="text-align: center; font-size: 18px; font-weight: bold; margin-top: 20px;">
<p><strong>MTH-208 COURSE PROJECT REPORT</strong></p>
<p><strong>GROUP 13</strong></p>
</div>
<div style="text-align: center; font-size: 16px; font-weight: bold; margin-top: 10px;">
<p><strong>INSTRUCTOR: DR. DOOTIKA VATS</strong></p>
</div>
<div style="text-align: center; font-size: 16px; font-weight: bold; margin-top: 10px;">
<p><strong>Group Members: KHUSHI LEKHWAR, SHRASTI DWIVEDI, LIPIKA BAGAI ,MAHESH PATEL</strong></p>
</div>
<hr>
<section id="table-of-contents" class="level2">
<h2 class="anchored" data-anchor-id="table-of-contents">Table of Contents</h2>
<ul>
<li><p>Acknowledgment</p></li>
<li><p>Introduction</p></li>
<li><p>Data Description</p></li>
<li><p>Data Extraction and Cleaning</p></li>
<li><p>Biases</p></li>
<li><p>Visualizations</p></li>
<li><p>Conclusion</p></li>
<li><p>References</p></li>
</ul>
</section>
<section id="acknowledgment" class="level2">
<h2 class="anchored" data-anchor-id="acknowledgment">Acknowledgment</h2>
<p>We, the students of group - 13 would like to express our profound gratitude towards <strong>Dr.&nbsp;Dootika Vats</strong>, our academic and project instructor for MTH208 (Data Science Lab I), for her guidance and constant supervision throughout the process and providing creative ideas and necessary information regarding the project which led to the completion of this project.</p>
<p>It has been a great learning experience and has also provided us with a practical insight of the theoretical knowledge gathered during the course lecture.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction:</h2>
<p>This project seeks to analyze the dataset on Paralympic athletes and their medal achievements, with the ultimate goal of creating a Shiny App to visualize and explore the various factors, including GDP of a country and gender participation, that influence the performance of a country in the Paralympics. The dataset encompasses athlete demographics, event categories, gender participation and medal counts for the Paralympics 2024, allowing for an in-depth analysis of trends and performance across the different countries, sports and etc.</p>
<p>This report highlights the data preparation, analysis and plots, as well as the insights gained about trends in Paralympics achievements across nations.</p>
</section>
<section id="a.-data-description" class="level2">
<h2 class="anchored" data-anchor-id="a.-data-description">A. Data Description</h2>
<p>Our app consists of the following datasets saved in RData files:</p>
<p><strong>1.Paralympics total Medal Tally</strong> :</p>
<p>It consists of an all-time medal table for all&nbsp;Summer Paralympic Games&nbsp;from 1960 to 2024 and medals of countries in Paralympics.</p>
<ul>
<li><p><strong>Source</strong>: The dataset was majorly scraped from the Wikipedia Page of 2024 Paralympics Medal Tally[<a href="https://en.wikipedia.org/wiki/All-time_Paralympic_Games_medal_table">1.</a>] .</p></li>
<li><p><strong>Observations</strong>: The all time medal wise performance of each country was observed.</p></li>
<li><p><strong>Variables</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable name</th>
<th style="text-align: right;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Country</td>
<td style="text-align: right;">Country name</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number_of_games_participated</td>
<td style="text-align: right;">Total no. of games participated a country participated in</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gold</td>
<td style="text-align: right;">Count of Gold medals won</td>
</tr>
<tr class="even">
<td style="text-align: left;">Silver</td>
<td style="text-align: right;">Count of Silver medals won</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bronze</td>
<td style="text-align: right;">Count of Bronze medals won</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">Count of Total medals won</td>
</tr>
</tbody>
</table></li>
</ul>
<p><strong>2.Countries.RData</strong> :</p>
<p>It consists of a participation of gender v/s sports table for top 16 countries that participated in&nbsp;Summer Paralympic Games 2024 and another table of medals v/s sports of the same countries in Paralympics.</p>
<ul>
<li><p><strong>Source</strong>: The dataset was majorly scraped from the Wikipedia Page of each country of 2024 Paralympics Medal<a href="https://en.wikipedia.org/wiki/India_at_the_2024_Summer_Paralympics">[2]</a>.</p></li>
<li><p><strong>Observations</strong>: The sport v/s gender-wise participation and sports v/s medal wise performance of each country was observed.</p></li>
<li><p><strong>Variables</strong>:</p>
<p>This data frame consisted of a table of 2 tables of a table i.e each country in the top 16 had 2 tables in it with the following variable names.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable name</th>
<th style="text-align: right;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sport</td>
<td style="text-align: right;">Sport name</td>
</tr>
<tr class="even">
<td style="text-align: left;">Men</td>
<td style="text-align: right;">No.&nbsp;of males that participated from a sport</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Women</td>
<td style="text-align: right;">No.&nbsp;of females that participated from a sport</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">Total no. of participants in each sport</td>
</tr>
</tbody>
</table></li>
</ul>
<p>The second table consisted of the following variables:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable name</th>
<th style="text-align: right;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sport</td>
<td style="text-align: right;">Sport name</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gold</td>
<td style="text-align: right;">No.&nbsp;of gold medals won in a sport</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Silver</td>
<td style="text-align: right;">No.&nbsp;of silver medals won in a sport</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bronze</td>
<td style="text-align: right;">No.&nbsp;of bronze medals won in each sport</td>
</tr>
</tbody>
</table>
<p><strong>3.Top80medaltally :</strong></p>
<p>It consists of the gender wise medal tally of Top 80 country that participated in Paralympics 2024</p>
<ul>
<li><p><strong>Source</strong>: The dataset was majorly sourced from a csv file obtained from the web<a href="https://womeninsport.org/wp-content/uploads/2024/09/Paris-Paralympic-2024-medal-table-3.pdf">[3]</a>.</p></li>
<li><p><strong>Observations</strong>: The gender-wise and medal wise performance of each country was observed.</p></li>
<li><p><strong>Variables</strong>:</p>
<p>This data frame consisted of a table with the following variable names:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: right;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Country</td>
<td style="text-align: right;">Country Name</td>
</tr>
<tr class="even">
<td>G_Female</td>
<td style="text-align: right;">Count of gold medals won by female</td>
</tr>
<tr class="odd">
<td>G_Male</td>
<td style="text-align: right;">Count of gold medals won by male</td>
</tr>
<tr class="even">
<td>G_Mixed</td>
<td style="text-align: right;">Count of gold medals won in mixed sports</td>
</tr>
<tr class="odd">
<td>S_Female</td>
<td style="text-align: right;">Count of silver medals won by female</td>
</tr>
<tr class="even">
<td>S_Male</td>
<td style="text-align: right;">Count of silver medals won by male</td>
</tr>
<tr class="odd">
<td>S_Mixed</td>
<td style="text-align: right;">Count of silver medals won in mixed sports</td>
</tr>
<tr class="even">
<td>B_Female</td>
<td style="text-align: right;">Count of bronze medals won by female</td>
</tr>
<tr class="odd">
<td>B_Male</td>
<td style="text-align: right;">Count of bronze medals won by male</td>
</tr>
<tr class="even">
<td>B_Mixed</td>
<td style="text-align: right;">Count of bronze medals won in mixed sports</td>
</tr>
<tr class="odd">
<td>T_Female</td>
<td style="text-align: right;">Count of total female medals won</td>
</tr>
<tr class="even">
<td>T_Male</td>
<td style="text-align: right;">Count of total male medals won</td>
</tr>
<tr class="odd">
<td>T_Mixed</td>
<td style="text-align: right;">Count of total mixed medals won</td>
</tr>
<tr class="even">
<td>T_Gold</td>
<td style="text-align: right;">Count of total gold medals won</td>
</tr>
<tr class="odd">
<td>T_Silver</td>
<td style="text-align: right;">Count of total silver medals won</td>
</tr>
<tr class="even">
<td>T_Bronze</td>
<td style="text-align: right;">Count of total bronze medals won</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">Count of total medals won</td>
</tr>
</tbody>
</table></li>
</ul>
<p><strong>4. GDP:</strong></p>
<p>It consists of the GDP (Gross Domestic Product) of each country measured in millions in 2022.</p>
<ul>
<li><p><strong>Source</strong>: The dataset was majorly sourced from the worldometer website<a href="https://www.worldometers.info/gdp/gdp-by-country/">[4]</a>.</p></li>
<li><p><strong>Observations</strong>: The GDP of each country was observed.</p></li>
</ul>
</section>
<section id="b.-obtaining-the-data" class="level2">
<h2 class="anchored" data-anchor-id="b.-obtaining-the-data">B. Obtaining the Data</h2>
<section id="data-collection" class="level3">
<h3 class="anchored" data-anchor-id="data-collection">Data Collection</h3>
<ul>
<li><p><strong>Web Scraping</strong>: The data was majorly scraped from website using R’s packages such as rvest, dplyr and tidy verse.</p></li>
<li><p><strong>CSV Data</strong>: The Paris-Paralympic-medal-table-2024.csv was obtained from the women in sport website.It was downloaded in pdf and then converted to csv using csv to pdf converter.</p></li>
<li><p><strong>Steps</strong>: The obtained data was then cleaned in ways such as changing data type from string to numeric for better handling, which was all done in R.</p>
<p>From the medal tally, only top 80 country were chosen because all the others had 0 medals and didn’t contribute to the plots/analysis.</p>
<p>Also, since on Wikipedia not all sites had country wise sports v/s participation tally and that is why only the Top 16 could be taken up.</p></li>
</ul>
</section>
</section>
<section id="c.identifying-any-biases-in-the-data." class="level2">
<h2 class="anchored" data-anchor-id="c.identifying-any-biases-in-the-data."><strong>C.Identifying any biases in the data.</strong></h2>
<p>Since the data was obtained from official sources, data collection bias appears minimal.But there may be bias in other forms such as the dataset primarily focuses on the top 16 or 80 countries, which could exclude smaller or less developed countries, potentially skewing results in favor of wealthier or more well-established nations with greater resources for athlete participation and training.</p>
<p>Additionally, there may be biases in gender representation, especially in sports where certain genders dominate. While the data presents male and female medal counts, it might not fully account for the accessibility and opportunities available to athletes based on gender.</p>
<p>Also, the dataset primarily covers athletes that participated in the 2024 Paralympics, but it may not include information on athletes who were unable to participate due to a lack of support, resources, or opportunities, particularly in low-income countries.</p>
</section>
<section id="d.interesting-questions-to-ask-from-the-data" class="level2">
<h2 class="anchored" data-anchor-id="d.interesting-questions-to-ask-from-the-data">D.Interesting Questions to ask from the data</h2>
<p>Specifically, in the analysis tried to address the following key questions:</p>
<p><strong>1. Athlete Participation and Country Performance:</strong> What is the level of athlete participation across different countries, and how does each country’s performance compare in terms of total medals won?</p>
<p><strong>2. Gender-Based Performance Comparison:</strong> How does gender influence performance across different countries? By calculating the performance ratio (number of medals won per participant) for each gender and examining its correlation with each country’s GDP, this project explored if economic factors contribute to gender-based performance differences.</p>
<p><strong>3.Gender and Medal Participation:</strong> Is there a significant correlation between the gender of athletes and the type of medal they won across different countries ?</p>
</section>
<section id="e.important-visualisations" class="level2">
<h2 class="anchored" data-anchor-id="e.important-visualisations">E.Important Visualisations</h2>
<p>The app is divided into three main tabs, providing unique visualizations and insights into our data:</p>
<section id="participation-by-gender" class="level4">
<h4 class="anchored" data-anchor-id="participation-by-gender">Participation By Gender:</h4>
<p>This tab provides insights into the participation of male and female athletes in various sports for a selected country , using bar plots visualizations in the main panel. It also includes heatmap that visualizes the <strong>distribution of medals</strong> across different sports and medal types (Gold, Silver, Bronze) for a selected country.</p>
<p>The bar plot effectively illustrates the number of male and female athletes participating in each sport , making it easier to compare gender representation at a glance.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>$df1
                   Sport Gold Silver Bronze Total
2               Swimming   22     21     11    54
3              Athletics   21     22     16    59
4           Table tennis   11      7      6    24
5     Wheelchair fencing   10      5      4    19
6              Badminton    9      2      1    12
7           Powerlifting    6      8      1    15
8                Cycling    5      4      1    10
9                Archery    3      3      2     8
10                  Judo    2      1      2     5
11              Shooting    2      1      2     5
12                Boccia    2      0      0     2
13             Taekwondo    1      0      0     1
14                Rowing    0      1      0     1
15    Sitting volleyball    0      1      0     1
16              Goalball    0      0      1     1
17          Paracanoeing    0      0      1     1
18 Wheelchair basketball    0      0      1     1
19     Wheelchair tennis    0      0      1     1
20                 Total   94     76     50   220

$df2
                   Sport Men Women Total
1                Archery   6     6    12
2              Athletics  20    31    51
3              Badminton   5     8    13
4                 Boccia   3     2     5
5                Cycling   4     4     8
6               Goalball   6     6    12
7                   Judo   1     6     7
8           Paracanoeing   2     3     5
9           Powerlifting   8     8    16
10                Rowing   3     4     7
11              Shooting   4     3     9
12    Sitting volleyball   0    12    12
13              Swimming   7    10    17
14          Table tennis  10    11    21
15             Taekwondo   1     3     4
16 Wheelchair basketball   0    12    12
17    Wheelchair fencing   6     6    12
18     Wheelchair tennis   3     4     7
19                 Total 126   158   284</code></pre>
</div>
</div>
<p>As is clear from the figures that a total of 126 men and 158 women participated across various sports, indicating a higher participation rate among female athletes in China.</p>
<p><strong>Athletics</strong> and <strong>Swimming</strong> have the highest total participation, with <strong>Athletics</strong> showing a higher number of women (31) compared to men(20).</p>
<p><strong>Sitting Volleyball</strong> and <strong>Wheelchair Basketball</strong> have no male participation suggesting the men are less likely to participate in the sport in China.</p>
<p><strong>Boccia</strong>, <strong>Paracanoeing</strong>, <strong>Judo</strong> and <strong>Taekwondo</strong> have the lowest overall participation, with fewer than 8 athletes in total for each indicating the sports are less popular among athletes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"Countries.Rdata"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>countries_dataset[[<span class="dv">1</span>]][[<span class="dv">2</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Sport Men Women Total
1                Archery   6     6    12
2              Athletics  20    31    51
3              Badminton   5     8    13
4                 Boccia   3     2     5
5                Cycling   4     4     8
6               Goalball   6     6    12
7                   Judo   1     6     7
8           Paracanoeing   2     3     5
9           Powerlifting   8     8    16
10                Rowing   3     4     7
11              Shooting   4     3     9
12    Sitting volleyball   0    12    12
13              Swimming   7    10    17
14          Table tennis  10    11    21
15             Taekwondo   1     3     4
16 Wheelchair basketball   0    12    12
17    Wheelchair fencing   6     6    12
18     Wheelchair tennis   3     4     7
19                 Total 126   158   284</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">=</span> countries_dataset[[<span class="dv">1</span>]][[<span class="dv">2</span>]]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the data to long format</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>dat_long <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(Men, Women), <span class="at">names_to =</span> <span class="st">"gender"</span>, <span class="at">values_to =</span> <span class="st">"participation"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>dat_long <span class="ot">&lt;-</span> dat_long <span class="sc">%&gt;%</span> <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span>(<span class="fu">n</span>() <span class="sc">-</span> <span class="dv">2</span>))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># View the reshaped data</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dat_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 36 × 4
   Sport     Total gender participation
   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;
 1 Archery      12 Men                6
 2 Archery      12 Women              6
 3 Athletics    51 Men               20
 4 Athletics    51 Women             31
 5 Badminton    13 Men                5
 6 Badminton    13 Women              8
 7 Boccia        5 Men                3
 8 Boccia        5 Women              2
 9 Cycling       8 Men                4
10 Cycling       8 Women              4
# ℹ 26 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_long, <span class="fu">aes</span>(<span class="at">x =</span> Sport, <span class="at">y =</span> participation, <span class="at">fill =</span> gender)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sport"</span>, <span class="at">y =</span> <span class="st">"Total Participation"</span>, <span class="at">title =</span> <span class="st">"Participation in Sports by Gender"</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">90</span>, <span class="at">vjust=</span><span class="fl">0.6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="group13_project_report_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The heatmap provides an at-a glance view of which sport yields the most medals and the type of medals won by the selected country. By using color intensity , the heatmap highlights the following:</p>
<p>1.<strong>Sports with higher or lower medal counts:</strong> Darker colors represent higher medal counts, while lighter colors indicate fewer medals.</p>
<p>2.<strong>Medal type breakdown:</strong> Rows represent different sports, and columns represent medal types (Gold, Silver and Bronze), allowing users to see the distribution across each category.</p>
<p>Given below is the medal tally for China. As is clear from the figures that Swimming is the sport wherein China won highest number of medals.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                   Sport Gold Silver Bronze Total
2               Swimming   22     21     11    54
3              Athletics   21     22     16    59
4           Table tennis   11      7      6    24
5     Wheelchair fencing   10      5      4    19
6              Badminton    9      2      1    12
7           Powerlifting    6      8      1    15
8                Cycling    5      4      1    10
9                Archery    3      3      2     8
10                  Judo    2      1      2     5
11              Shooting    2      1      2     5
12                Boccia    2      0      0     2
13             Taekwondo    1      0      0     1
14                Rowing    0      1      0     1
15    Sitting volleyball    0      1      0     1
16              Goalball    0      0      1     1
17          Paracanoeing    0      0      1     1
18 Wheelchair basketball    0      0      1     1
19     Wheelchair tennis    0      0      1     1
20                 Total   94     76     50   220</code></pre>
</div>
</div>
<p>Heatmap visualization makes it even easier to make this observation.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="group13_project_report_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>World Map and GDP Analysis</strong></p>
<p>In this section, the medal/participation ratio was plotted against GDP of different countries worldwide among the Top16 countries and whoever had more medals that gender’s bubble plot was plotted.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="group13_project_report_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the plot , it could easily be inferred that in high GDP country “Performance Ratio” of females was better ,i.e female para-athletes performed better which can be due to them getting better resources in these countries.</p>
</section>
<section id="countries-comparison" class="level4">
<h4 class="anchored" data-anchor-id="countries-comparison">Countries Comparison</h4>
<p>Here , all the countries were compared against each other in terms of medal tally and participation.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="group13_project_report_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The correlation found for this data was 0.84 between total participation and total medals.</p>
</section>
</section>
<section id="f.final-conclusions" class="level2">
<h2 class="anchored" data-anchor-id="f.final-conclusions">F.Final Conclusions</h2>
<p>While it may seem that women might not participate more than men(overall) in sports but when they do, their performance ratio(medal/participation) was higher a lot of times depicting that when invested in them such as done in high-GDP countries, they could reap great results.</p>
<p>Another inference was the participation v/s medal count , it seemed that no. of participants and no. of medals had direct correlation.While this could be not always be right too because it was only the best athletes participate from a country and also due to the limitation of dataset here (i.e.&nbsp;a small dataset )of 16 high performing countries.</p>
</section>
<section id="g.references" class="level2">
<h2 class="anchored" data-anchor-id="g.references">G.References</h2>
<p>1.<a href="https://en.wikipedia.org/wiki/All-time_Paralympic_Games_medal_table" class="uri">https://en.wikipedia.org/wiki/All-time_Paralympic_Games_medal_table</a></p>
<p>2.<a href="https://en.wikipedia.org/wiki/India_at_the_2024_Summer_Paralympics" class="uri">https://en.wikipedia.org/wiki/India_at_the_2024_Summer_Paralympics</a></p>
<p>3.<a href="https://womeninsport.org/wp-content/uploads/2024/09/Paris-Paralympic-2024-medal-table-3.pdf" class="uri">https://womeninsport.org/wp-content/uploads/2024/09/Paris-Paralympic-2024-medal-table-3.pdf</a></p>
<p>4.<a href="https://www.worldometers.info/gdp/gdp-by-country/" class="uri">https://www.worldometers.info/gdp/gdp-by-country/</a></p>
<p>5. R Help Tab and libraries</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>